env:
  - CXX=g++-4.8 COVERALLS_REPO_TOKEN=PXOsSus6WfsvwzKISEadhGBZONtz6asEm
language: node_js
node_js:
  - "6"

addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
    - gcc-4.8
    - g++-4.8

services:
  - docker

script: cd back && npm install && npm run itest && cd ../web && npm install && npm test