version: "2"

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=skillz
      - MYSQL_USER=skillz
      - MYSQL_PASSWORD=skillz
    ports:
      - 3306:3306
    networks:
      - backend

  back:
    build: ./back
    image: xebiafrance/skillz-back
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

  web:
    build: ./web
    image: xebiafrance/skillz-web
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend: